# Compose file for local development and testing. Images are built from
# local directories which need to be cloned from the repository.
version: '3.7'

x-env-php: &env-php
  PHP_VERSION: 7.4.19


services:
  traefik:
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

  testcenter-db:
    ports:
      - "9091:3306"

  testcenter-backend:
    build:
      context: testcenter-backend
      dockerfile: docker/Dockerfile
      args:
        <<: *env-php
    volumes:
      - ./testcenter-backend/classes:/var/www/html/classes
      - ./testcenter-backend/definitions:/var/www/html/definitions
      - ./testcenter-backend/docs/specs.yml:/var/www/html/docs/specs.yml
      - ./testcenter-backend/routes:/var/www/html/routes
      - ./testcenter-backend/sampledata:/var/www/html/sampledata
      - ./testcenter-backend/vo_data:/var/www/html/vo_data
      - ./testcenter-backend/vendor:/var/www/html/vendor
      - ./testcenter-backend/composer.json:/var/www/html/composer.json
      - ./testcenter-backend/composer.lock:/var/www/html/composer.lock

  testcenter-frontend:
    build:
      context: testcenter-frontend
      dockerfile: docker/Dockerfile
      target: dev
    volumes:
      - ./testcenter-frontend:/app
      - testcenter_frontend_node_modules:/app/node_modules

  testcenter-broadcasting-service:
    build:
      context: testcenter-broadcasting-service
      dockerfile: docker/Dockerfile


volumes:
  testcenter_frontend_node_modules:
